buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
  }
}

allprojects {
  ext {
    gdxVersion = '1.12.1'
    projectVersion = '1.0'
    appName = 'NoClassTodayGame'
  }

  repositories {
    mavenCentral()
    maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
  }

  apply plugin: 'idea'
  idea {
    module {
      outputDir = file('build/classes/java/main')
      testOutputDir = file('build/classes/java/test')
    }
  }
}

configure(subprojects) {
  apply plugin: 'java-library'
  java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }

  tasks.register('generateAssetList') {
    inputs.dir("${project.rootDir}/assets/")
    doLast {
      File assetsFolder = new File("${project.rootDir}/assets/")
      File assetsFile = new File(assetsFolder, "assets.txt")
      assetsFile.delete()
      fileTree(assetsFolder).collect { assetsFolder.relativePath(it) }.sort().each {
        assetsFile.append(it + "\n")
      }
    }
  }
  processResources.dependsOn 'generateAssetList'

  compileJava.options.incremental = true
}

// 👇 关键：下面这行必须删掉，你现在报错就是因为它
// eclipse.project.name = appName + '-parent'
