plugins {
  id 'java-library'
}

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}

sourceSets.main.resources.srcDirs += ["../assets"]

dependencies {
  api "com.badlogicgames.gdx:gdx:1.14.1"
  api "com.badlogicgames.gdx:gdx-platform:1.14.1:natives-desktop"
}
